# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Push workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Commit report
        run: |
          git config --global user.name 'npm release'
          git config --global user.email 'app.teamy.dev@gmail.com'
      - name: Installed packages
        run: npm install
      - name: Build components
        run: npm build
      - name: Publish package
        run: npm run publish:lib
        env:
          NODE_AUTH_TOKEN: ${{secrets.TEAMY_SECRET}}
